hw_10_website/hw_10_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw_10_website/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main"),
    path("page/<int:page>", views.MainPageView.as_view(), name="paginator"),
    path("new_author", views.CreateAuthorView.as_view(), name="author"),
    path("new_quote", views.CreateQuoteView.as_view(), name="quote"),
    path("profile/<int:author_id>", views.ProfileView.as_view(), name="profile"),
    path("tag/<str:tag_name>", views.QuotesByTag.as_view(), name="tag"),
    path("tag/<str:tag_name>/page/<int:page>", views.QuotesByTag.as_view(), name="tag_paginator"),
]

hw_10_website/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("signup/", views.SignUpUserView.as_view(), name="signup"),
    path("logout/", views.LogoutUserView.as_view(), name="logout"),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_10_website/quotes/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=50, unique=True)
    description = models.TextField(null=True)
    born_date = models.DateField(null=True)
    born_location = models.CharField(max_length=100, null=True)
    photo = models.ImageField(default='default_image.png', upload_to='profile_images', null=True)

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.photo.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.photo.path)

    def __str__(self):
        return f"{self.fullname}"


class Quote(models.Model):
    quote = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, through="QuoteTag")
    author = models.ForeignKey(Author, on_delete=models.PROTECT, related_name="quotes")


class QuoteTag(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

hw_10_website/quotes/forms.py
from django import forms
from django.forms import SelectDateWidget
from datetime import datetime
from .models import Author, Tag, Quote


class CustomSelectDateWidget(SelectDateWidget):
    def __init__(self, attrs=None, years=None, required=False):
        this_year = datetime.now().year
        if years is None:
            years = range(this_year, this_year - 100, -1)  # Годы в обратном порядке на 100 лет назад
        super().__init__(attrs, years, required)
        self.is_required = required


class AuthorCreateForm(forms.ModelForm):
    fullname = forms.CharField(max_length=50, widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}), required=False)
    born_date = forms.DateField(widget=CustomSelectDateWidget, required=False)
    born_location = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class": "form-control"}), required=False)
    photo = forms.ImageField(required=False)

    class Meta:
        model = Author
        fields = ['fullname', 'description', 'born_date', 'born_location', 'photo']


class QuoteCreateForm(forms.ModelForm):
    quote = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))
    tags = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(attrs={"class": "form-control"}), queryset=Tag.objects.all())
    author = forms.ModelChoiceField(widget=forms.Select(attrs={"class": "form-control"}), queryset=Author.objects.all())

    class Meta:
        model = Quote

        exclude = ["created"]

hw_10_website/quotes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, DetailView
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db.models import Count


from .models import Quote, Author, QuoteTag, Tag
from .forms import AuthorCreateForm, QuoteCreateForm


# Create your views here.
class CustomMixIn:
    model = Quote
    template_name = "quotes/index.html"
    context_object_name = "quote_list"
    ordering = "-created"
    paginate_by = 10

    def top_tags(self):
        top_tags_id = QuoteTag.objects.values('tag_id').annotate(tag_count=Count('tag_id')).order_by('-tag_count')[:10]

        top_tags_name = []
        for tag in top_tags_id:
            top_tags_name.append(Tag.objects.get(id=tag["tag_id"]))

        return top_tags_name


class MainPageView(CustomMixIn, ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["top_tags"] = self.top_tags()
        return context


class CreateAuthorView(LoginRequiredMixin, CreateView):
    model = Author
    template_name = "quotes/author.html"
    form_class = AuthorCreateForm

    def get_success_url(self):
        return reverse("quotes:main")


class CreateQuoteView(LoginRequiredMixin, CreateView):
    model = Quote
    template_name = "quotes/quote.html"
    form_class = QuoteCreateForm

    def get_success_url(self):
        return reverse("quotes:main")


class ProfileView(DetailView):
    model = Author
    template_name = "quotes/profile.html"
    context_object_name = "author"

    def get_object(self, queryset=None):
        pk = self.kwargs.get("author_id")
        return get_object_or_404(Author, id=pk)


class QuotesByTag(CustomMixIn, ListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["top_tags"] = self.top_tags()
        return context

    def get_queryset(self):
        tag_name = self.kwargs["tag_name"]
        tag_object = Tag.objects.get(name=tag_name)

        quotes = Quote.objects.filter(tags=tag_object)
        return quotes

hw_10_website/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-6">
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
                <div class="card border-0 shadow">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4">New Author</h2>
                        <form method="post" novalidate enctype="multipart/form-data">

                            {% csrf_token %}

                            <div class="form-group">
                                <label for="{{ form.fullname.id_for_label }}" class="form-label">
                                    {{ form.fullname.label }}
                                </label>
                                {{ form.fullname }}
                                {% for error in form.fullname.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>

                            <div class="form-group">
                                  <label for="{{ form.description.id_for_label }}" class="form-label">
                                      Biography
                                  </label>
                                  {{ form.description }}
                                  {% for error in form.description.errors %}
                                      <div class="alert alert-danger">{{ error }}</div>
                                  {% endfor %}
                            </div>

                            <div class="form-group">
                                    <label for="{{ form.born_date.id_for_label }}" class="form-label">
                                        {{ form.born_date.label }}
                                    </label>
                                    {{ form.born_date }}
                                    {% for error in form.born_date.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                            </div>

                            <div class="form-group">
                                    <label for="{{ form.born_location.id_for_label }}" class="form-label">
                                        {{ form.born_location.label }}
                                    </label>
                                    {{ form.born_location }}
                                    {% for error in form.born_location.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                            </div>


                            <div class="form-group">
                                    <label for="{{ form.photo.id_for_label }}" class="form-label">
                                        {{ form.photo.label }}
                                    </label>
                                    {{ form.photo }}
                                    {% for error in form.photo.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                            </div>

                            <br>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <button type="reset" class="btn btn-warning">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

hw_10_website/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="ru-UA">
<head>
    <title>
        {% block title %}
            {% if title %}
                {{ title }}
            {% else %}
                Quotes
            {% endif %}
        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'quotes:main' %}">Quotes</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">

                {% if user.is_authenticated %}
                    <li class="nav-item{% if active == 'index' %} active{% endif %}">
                        <a class="nav-link" href="{% url 'quotes:quote' %}">Add quote</a>
                    </li>
                    <li class="nav-item{% if active == 'index' %} active{% endif %}">
                        <a class="nav-link" href="{% url 'quotes:author' %}">Add new author</a>
                    </li>
                {% endif %}

            </ul>
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item me-2">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a></li>
                <li class="nav-item me-2" >
                    <p class="nav-link"> Welcome, {{ user.username }}! </p></li>

                {% else %}
                <li class="nav-item me-2">
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
                <li class="nav-item me-2">
                    <a class="nav-link" href="{% url 'users:signup' %}">Sign up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="mt-4">
<div class="container">
    {% block content %}

    {% endblock %}
</div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous">
</script>
</body>
</html>

hw_10_website/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% for quote in quote_list %}
                    <div class="card mb-3">
                        <div class="card-body d-flex align-items-center">
                            <div>
                                <div>
                                    <p class="card-text">{{ quote.quote }}</p>
                                </div>
                            </div>
                        </div>
                              <div class="card-footer">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="d-flex align-items">
                                        <span>Author: <a href="{% url 'quotes:profile' quote.author.id %}"
                                                         class="clickable-text"> {{ quote.author.fullname }} </a> </span>
                                    </div>
                                    {% if quote.tags.all %}
                                    <div class="d-flex align-items-center">
                                        <span>Tags:
                                            {% for tag in quote.tags.all %}
                                                <a href="{% url 'quotes:tag' tag.name %}" class="clickable-text">{{ tag.name }}</a>
                                                {% endfor %}
                                        </span>
                                    </div>
                                {% endif %}

                            </div>
    </div>

                    </div>
                {% endfor %}
            </div>


        <div class="col-md-4 tags-box">

            {% include "quotes/top_tags.html" with top_tags=top_tags %}

        </div>

        </div>
    </div>

<div>
    <nav>
        <ul class="pager">

            <li class="previous">
                <a {% if not page_obj.has_previous %} disabled {% endif %}
                href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }} {% else %} # {% endif %}">
                    Previous <span aria-hidden="true">←</span>
            </li>

            <li class="next">
                <a class="{% if not page_obj.has_next %} disabled {% endif %}"
                   href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span>
                </a>
            </li>

        </ul>
    </nav>
</div>

{% endblock %}

hw_10_website/quotes/templates/quotes/profile.html
{% extends 'quotes/base.html' %}

{% block content %}

    <div class="author-details">
        <br>
        <div class="row">
            <div class="col-md-4">
                {% if "http" in author.photo.url %}
                    <img src="{{ author.photo }}" class="img-thumbnail mb-3" alt="{{ author.fullname }}">
                {% else %}
                    <img src="{{ author.photo.url }}" class="img-thumbnail mb-3" alt="{{ author.fullname }}">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="d-flex align-items-center justify-content-between">
                <h3 class="author-title">{{ author.fullname }}</h3>

                </div>
                <p>
                <strong>Born:</strong>
                <span class="author-born-date">{{ author.born_date }} - </span>
                <span class="author-born-location">{{ author.born_location }}</span>
                </p>
                <p>
                    <strong>Biography:</strong>
                    <span>{{ author.description }} </span>
                </p>

            </div>

        </div>
    </div>

{% endblock %}

hw_10_website/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-6">
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
                <div class="card border-0 shadow">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4">Adding new quote</h2>
                        <form method="post" novalidate enctype="multipart/form-data">

                            {% csrf_token %}

                            <div class="form-group">
                                <label for="{{ form.author.id_for_label }}" class="form-label">
                                    {{ form.author.label }}
                                </label>
                                {{ form.author }}
                                {% for error in form.author.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>

                            <div class="form-group">
                                  <label for="{{ form.quote.id_for_label }}" class="form-label">
                                      Quote
                                  </label>
                                  {{ form.quote }}
                                  {% for error in form.quote.errors %}
                                      <div class="alert alert-danger">{{ error }}</div>
                                  {% endfor %}
                            </div>

                            <div class="form-group">
                                    <label for="{{ form.tags.id_for_label }}" class="form-label">
                                        Select tags
                                    </label>
                                    {{ form.tags }}
                                    {% for error in form.tags.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                            </div>
                            <br>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <button type="reset" class="btn btn-warning">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

hw_10_website/quotes/templates/quotes/top_tags.html
<h2>Top Ten tags</h2>

{% for tag in top_tags %}

    <span class="tag-item">
        • <a class="tag" href="{% url 'quotes:tag' tag.name %}"> {{ tag.name }}</a>
    <br>
    </span>

{% endfor %}