hw_10_website/hw_10_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw_10_website/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("signup/", views.SignUpUserView.as_view(), name="signup"),
    path("logout/", views.LogoutUserView.as_view(), name="logout"),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_10_website/users/models.py
from django.db import models

# Create your models here.

hw_10_website/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'password']


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=16, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))

    email = forms.EmailField(max_length=100,
                             required=True,
                             widget=forms.TextInput())

    password1 = forms.CharField(max_length=16, required=True,
                                widget=forms.PasswordInput(attrs={"class": "form-control"}))

    password2 = forms.CharField(max_length=16, required=True,
                                widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

hw_10_website/users/views.py
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.views.generic import CreateView
from django.contrib.messages.views import SuccessMessageMixin

from .forms import LoginForm, SignUpForm


# Create your views here.
class LoginUserView(LoginView):
    template_name = "users/login.html"
    form_class = LoginForm
    next_page = "/"


class SignUpUserView(CreateView):
    template_name = "users/signup.html"
    form_class = SignUpForm

    def get_success_url(self):
        return reverse("users:login")


class LogoutUserView(LogoutView):
    next_page = "/"


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

hw_10_website/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-6">
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
                <div class="card border-0 shadow">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4">Login</h2>
                        <form method="post" novalidate>

                            {% csrf_token %}

                            <div class="form-group">
                                <label for="{{ form.username.id_for_label }}" class="form-label">
                                    {{ form.username.label }}
                                </label>
                                {{ form.username }}
                                {% for error in form.username.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.password.id_for_label }}" class="form-label">
                                    {{ form.password.label }}
                                </label>
                                {{ form.password }}
                                {% for error in form.password.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <br>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Login</button>
                                <button type="reset" class="btn btn-warning">Reset</button>
                            </div>
                            <div class="small text-center">
                                <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

hw_10_website/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hw_10_website/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hw_10_website/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw_10_website/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw_10_website/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="http://127.0.0.1:8000/users/reset-password/confirm/{{ uid }}/{{ token }}/">
        Reset password
    </a>


</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hw_10_website/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-6">
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
                <div class="card border-0 shadow">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4">Sign Up</h2>
                        <form method="post" novalidate>

                            {% csrf_token %}

                            <div class="form-group">
                                <label for="{{ form.username.id_for_label }}" class="form-label">
                                    {{ form.username.label }}
                                </label>
                                {{ form.username }}
                                {% for error in form.username.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.email.id_for_label }}" class="form-label">
                                    Email:
                                </label><br>
                                {{ form.email }}
                                {% for error in form.email.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.password.id_for_label }}" class="form-label">
                                    Password:
                                </label>
                                {{ form.password1 }}

                                <label for="{{ form.password.id_for_label }}" class="form-label">
                                    Password confirmation:
                                </label>
                                {{ form.password2 }}
                                {% for error in form.password.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <br>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Sign Up</button>
                                <button type="reset" class="btn btn-warning">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}